log: log/thin.log
timeout: 30
max_conns: 1024
port: 3000
max_persistent_conns: 512
chdir: /var/www/sites/metacraft/current
environment: production
threaded: true
no-epoll: true
daemonize: true
servers: 1
address: 0.0.0.0
daemonize: true